In [ ]:
from google.colab import drive, files
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [ ]:
#Baixando os datasets

!gdown 1IpgwvO3GSik8cb0XbjY3mJr_WCmVazm6
!gdown 17e1rDWW3o9tDqz5d1uSTYacqBX1ziAaj
!gdown 16GtwYqtKpYcRZIhfXZaoWBHlHl4_-qtn

Downloading...
From: https://drive.google.com/uc?id=1IpgwvO3GSik8cb0XbjY3mJr_WCmVazm6
To: /content/tv_0_anon.csv
100% 81.3M/81.3M [00:00<00:00, 224MB/s]
Downloading...
From: https://drive.google.com/uc?id=17e1rDWW3o9tDqz5d1uSTYacqBX1ziAaj
To: /content/tv_1_anon.csv
100% 77.2M/77.2M [00:00<00:00, 210MB/s]
Downloading...
From: https://drive.google.com/uc?id=16GtwYqtKpYcRZIhfXZaoWBHlHl4_-qtn
To: /content/tv_2_anon.csv
100% 77.3M/77.3M [00:00<00:00, 229MB/s]

In [ ]:
#Abrindo CSV'S
import pandas as pd
import numpy as np

tv_0_with_rat = pd.read_csv("/content/tv_0_anon.csv", encoding="UTF-8")
tv_1_with_rat = pd.read_csv("/content/tv_1_anon.csv", encoding="UTF-8")
tv_2_with_rat = pd.read_csv("/content/tv_2_anon.csv", encoding="UTF-8")

In [ ]:
tv_0_with_rat.head(8)

,Unnamed: 0,Unnamed: 0.1,Data,Hora Início,Emissora,Mês,Dia do Mês,Dia da Semana,Total Domicílios | Rat%,AB | Rat%,...,Feminino | Fid%,4-11 anos | Fid%,12-17 anos | Fid%,18-24 anos | Fid%,25-34 anos | Fid%,35-49 anos | Fid%,50-59 anos | Fid%,60+ anos | Fid%,Programa,Categoria
0,0,0,2020-06-01,06:00:00,tv_0,Junho,1,Segunda,4.27,2.40,...,89.84,0.0,0.0,0.0,100.0,69.20,100.00,84.31,0.1,JORNALISMO
1,1,1,2020-06-01,06:05:00,tv_0,Junho,1,Segunda,4.89,3.02,...,93.16,0.0,0.0,0.0,100.0,100.00,100.00,76.90,0.1,JORNALISMO
2,2,2,2020-06-01,06:10:00,tv_0,Junho,1,Segunda,5.74,3.13,...,94.63,0.0,80.0,0.0,100.0,84.24,100.00,84.60,0.1,JORNALISMO
3,3,3,2020-06-01,06:15:00,tv_0,Junho,1,Segunda,6.55,3.06,...,96.76,0.0,100.0,0.0,100.0,86.67,89.87,100.00,0.1,JORNALISMO
4,4,4,2020-06-01,06:20:00,tv_0,Junho,1,Segunda,7.27,3.49,...,100.00,0.0,100.0,0.0,100.0,95.22,93.24,100.00,0.1,JORNALISMO
5,5,5,2020-06-01,06:25:00,tv_0,Junho,1,Segunda,8.34,4.52,...,97.46,0.0,100.0,0.0,100.0,100.00,100.00,90.16,0.1,JORNALISMO
6,6,6,2020-06-01,06:30:00,tv_0,Junho,1,Segunda,7.74,3.44,...,88.32,0.0,100.0,0.0,100.0,92.35,66.50,91.17,0.1,JORNALISMO
7,7,7,2020-06-01,06:35:00,tv_0,Junho,1,Segunda,6.96,3.92,...,91.18,0.0,100.0,0.0,100.0,100.00,100.00,68.25,0.1,JORNALISMO


#Removendo colunas que não serão usadas

In [ ]:
tv_0_clear_rat = tv_0_with_rat.drop(tv_0_with_rat.iloc[:,36: 50], axis = 1 )
tv_1_clear_rat = tv_1_with_rat.drop(tv_1_with_rat.iloc[:,36: 50], axis = 1 )
tv_2_clear_rat = tv_2_with_rat.drop(tv_2_with_rat.iloc[:,36: 50], axis = 1 )

tv_0_clear_rat.columns

Index(['Unnamed: 0', 'Unnamed: 0.1', 'Data', 'Hora Início', 'Emissora', 'Mês',
       'Dia do Mês', 'Dia da Semana', 'Total Domicílios | Rat%', 'AB | Rat%',
       'C1 | Rat%', 'C2 | Rat%', 'DE | Rat%', 'Masculino | Rat%',
       'Feminino | Rat%', '4-11 anos | Rat%', '12-17 anos | Rat%',
       '18-24 anos | Rat%', '25-34 anos | Rat%', '35-49 anos | Rat%',
       '50-59 anos | Rat%', '60+ anos | Rat%', 'Total Domicílios | Shr%',
       'AB | Shr%', 'C1 | Shr%', 'C2 | Shr%', 'DE | Shr%', 'Masculino | Shr%',
       'Feminino | Shr%', '4-11 anos | Shr%', '12-17 anos | Shr%',
       '18-24 anos | Shr%', '25-34 anos | Shr%', '35-49 anos | Shr%',
       '50-59 anos | Shr%', '60+ anos | Shr%', 'Total Indivíduos | Fid%',
       'AB | Fid%', 'C1 | Fid%', 'C2 | Fid%', 'DE | Fid%', 'Masculino | Fid%',
       'Feminino | Fid%', '4-11 anos | Fid%', '12-17 anos | Fid%',
       '18-24 anos | Fid%', '25-34 anos | Fid%', '35-49 anos | Fid%',
       '50-59 anos | Fid%', '60+ anos | Fid%', 'Programa', 'Categoria'],
      dtype='object')

In [ ]:
#Removendo colunas especificas 
tv_0_clear_rat.drop(['Unnamed: 0', 'Unnamed: 0.1'], axis=1, inplace=True)
tv_1_clear_rat.drop(['Unnamed: 0', 'Unnamed: 0.1'], axis=1, inplace=True)
tv_2_clear_rat.drop(['Unnamed: 0', 'Unnamed: 0.1'], axis=1, inplace=True)

#Convertendo valores para inteiros e trocando qualitativos em quantitativos

In [ ]:
tv_0_with_rat['Dia da Semana'].unique()

array(['Segunda', 'Terça', 'Quarta', 'Quinta', 'Sexta', 'Sábado',
       'Domingo'], dtype=object)

In [ ]:
# Função que converte os valores a partir de um dicionário e ajusta o ano do programa

def dictionary(data):
    month = {'Janeiro':1, 'Fevereiro':2, 'Março':3, 'Abril':4, 'Maio':5, 'Junho':6, 'Julho':7, 'Agosto':8, 'Setembro':9, 'Outubro':10, 'Novembro':11, 'Dezembro':12}
    day_week = {'Segunda':1, 'Terça':2, 'Quarta':3,'Quinta':4,'Sexta':5,'Sábado': 6 , 'Domingo': 7 }
    start_hour = {'06:00:00': 6.0, '06:05:00': 6.05, '06:10:00': 6.1, '06:15:00': 6.15, '06:20:00': 6.2, '06:25:00': 6.25, '06:30:00': 6.3, '06:35:00': 6.35, '06:40:00': 6.4, '06:45:00': 6.45, '06:50:00': 6.5, '06:55:00': 6.55,
                  '07:00:00': 7.0, '07:05:00': 7.05, '07:10:00': 7.1, '07:15:00': 7.15, '07:20:00': 7.2, '07:25:00': 7.25, '07:30:00': 7.3, '07:35:00': 7.35, '07:40:00': 7.4, '07:45:00': 7.45, '07:50:00': 7.5, '07:55:00': 7.55,
                  '08:00:00': 8.0, '08:05:00': 8.05, '08:10:00': 8.1, '08:15:00': 8.15, '08:20:00': 8.2, '08:25:00': 8.25, '08:30:00': 8.3, '08:35:00': 8.35, '08:40:00': 8.4, '08:45:00': 8.45, '08:50:00': 8.5, '08:55:00': 8.55, 
                  '09:00:00': 9.0, '09:05:00': 9.05, '09:10:00': 9.1, '09:15:00': 9.15, '09:20:00': 9.2, '09:25:00': 9.25, '09:30:00': 9.3, '09:35:00': 9.35, '09:40:00': 9.4, '09:45:00': 9.45, '09:50:00': 9.5, '09:55:00': 9.55, 
                  '10:00:00': 10.0, '10:05:00': 10.05, '10:10:00': 10.1, '10:15:00': 10.15, '10:20:00': 10.2, '10:25:00': 10.25, '10:30:00': 10.3, '10:35:00': 10.35, '10:40:00': 10.4, '10:45:00': 10.45, '10:50:00': 10.5, '10:55:00': 10.55, 
                  '11:00:00': 11.0, '11:05:00': 11.05, '11:10:00': 11.1, '11:15:00': 11.15, '11:20:00': 11.2, '11:25:00': 11.25, '11:30:00': 11.3, '11:35:00': 11.35, '11:40:00': 11.4, '11:45:00': 11.45, '11:50:00': 11.5, '11:55:00': 11.55, 
                  '12:00:00': 12.0, '12:05:00': 12.05, '12:10:00': 12.1, '12:15:00': 12.15, '12:20:00': 12.2, '12:25:00': 12.25, '12:30:00': 12.3, '12:35:00': 12.35, '12:40:00': 12.4, '12:45:00': 12.45, '12:50:00': 12.5, '12:55:00': 12.55, 
                  '13:00:00': 13.0, '13:05:00': 13.05, '13:10:00': 13.1, '13:15:00': 13.15, '13:20:00': 13.2, '13:25:00': 13.25, '13:30:00': 13.3, '13:35:00': 13.35, '13:40:00': 13.4, '13:45:00': 13.45, '13:50:00': 13.5, '13:55:00': 13.55,
                  '14:00:00': 14.0, '14:05:00': 14.05, '14:10:00': 14.1, '14:15:00': 14.15, '14:20:00': 14.2, '14:25:00': 14.25, '14:30:00': 14.3, '14:35:00': 14.35, '14:40:00': 14.4, '14:45:00': 14.45, '14:50:00': 14.5, '14:55:00': 14.55, 
                  '15:00:00': 15.0, '15:05:00': 15.05, '15:10:00': 15.1, '15:15:00': 15.15, '15:20:00': 15.2, '15:25:00': 15.25, '15:30:00': 15.3, '15:35:00': 15.35, '15:40:00': 15.4, '15:45:00': 15.45, '15:50:00': 15.5, '15:55:00': 15.55, 
                  '16:00:00': 16.0, '16:05:00': 16.05, '16:10:00': 16.1, '16:15:00': 16.15, '16:20:00': 16.2, '16:25:00': 16.25, '16:30:00': 16.3, '16:35:00': 16.35, '16:40:00': 16.4, '16:45:00': 16.45, '16:50:00': 16.5, '16:55:00': 16.55, 
                  '17:00:00': 17.0, '17:05:00': 17.05, '17:10:00': 17.1, '17:15:00': 17.15, '17:20:00': 17.2, '17:25:00': 17.25, '17:30:00': 17.3, '17:35:00': 17.35, '17:40:00': 17.4, '17:45:00': 17.45, '17:50:00': 17.5, '17:55:00': 17.55,
                  '18:00:00': 18.0, '18:05:00': 18.05, '18:10:00': 18.1, '18:15:00': 18.15, '18:20:00': 18.2, '18:25:00': 18.25, '18:30:00': 18.3, '18:35:00': 18.35, '18:40:00': 18.4, '18:45:00': 18.45, '18:50:00': 18.5, '18:55:00': 18.55,
                  '19:00:00': 19.0, '19:05:00': 19.05, '19:10:00': 19.1, '19:15:00': 19.15, '19:20:00': 19.2, '19:25:00': 19.25, '19:30:00': 19.3, '19:35:00': 19.35, '19:40:00': 19.4, '19:45:00': 19.45, '19:50:00': 19.5, '19:55:00': 19.55,
                  '20:00:00': 20.0, '20:05:00': 20.05, '20:10:00': 20.1, '20:15:00': 20.15, '20:20:00': 20.2, '20:25:00': 20.25, '20:30:00': 20.3, '20:35:00': 20.35, '20:40:00': 20.4, '20:45:00': 20.45, '20:50:00': 20.5, '20:55:00': 20.55, 
                  '21:00:00': 21.0, '21:05:00': 21.05, '21:10:00': 21.1, '21:15:00': 21.15, '21:20:00': 21.2, '21:25:00': 21.25, '21:30:00': 21.3, '21:35:00': 21.35, '21:40:00': 21.4, '21:45:00': 21.45, '21:50:00': 21.5, '21:55:00': 21.55,
                  '22:00:00': 22.0, '22:05:00': 22.05, '22:10:00': 22.1, '22:15:00': 22.15, '22:20:00': 22.2, '22:25:00': 22.25, '22:30:00': 22.3, '22:35:00': 22.35, '22:40:00': 22.4, '22:45:00': 22.45, '22:50:00': 22.5, '22:55:00': 22.55, 
                  '23:00:00': 23.0, '23:05:00': 23.05, '23:10:00': 23.1, '23:15:00': 23.15, '23:20:00': 23.2, '23:25:00': 23.25, '23:30:00': 23.3, '23:35:00': 23.35, '23:40:00': 23.4, '23:45:00': 23.45, '23:50:00': 23.5, '23:55:00': 23.55, 
                  '24:00:00': 24.0, '24:05:00': 24.05, '24:10:00': 24.1, '24:15:00': 24.15, '24:20:00': 24.2, '24:25:00': 24.25, '24:30:00': 24.3, '24:35:00': 24.35, '24:40:00': 24.4, '24:45:00': 24.45, '24:50:00': 24.5, '24:55:00': 24.55, 
                  '25:00:00': 25.0, '25:05:00': 25.05, '25:10:00': 25.1, '25:15:00': 25.15, '25:20:00': 25.2, '25:25:00': 25.25, '25:30:00': 25.3, '25:35:00': 25.35, '25:40:00': 25.4, '25:45:00': 25.45, '25:50:00': 25.5, '25:55:00': 25.55, 
                  '26:00:00': 26.0, '26:05:00': 26.05, '26:10:00': 26.1, '26:15:00': 26.15, '26:20:00': 26.2, '26:25:00': 26.25, '26:30:00': 26.3, '26:35:00': 26.35, '26:40:00': 26.4, '26:45:00': 26.45, '26:50:00': 26.5, '26:55:00': 26.55, 
                  '27:00:00': 27.0, '27:05:00': 27.05, '27:10:00': 27.1, '27:15:00': 27.15, '27:20:00': 27.2, '27:25:00': 27.25, '27:30:00': 27.3, '27:35:00': 27.35, '27:40:00': 27.4, '27:45:00': 27.45, '27:50:00': 27.5, '27:55:00': 27.55,
                  '28:00:00': 28.0, '28:05:00': 28.05, '28:10:00': 28.1, '28:15:00': 28.15, '28:20:00': 28.2, '28:25:00': 28.25, '28:30:00': 28.3, '28:35:00': 28.35, '28:40:00': 28.4, '28:45:00': 28.45, '28:50:00': 28.5, '28:55:00': 28.55, 
                  '29:00:00': 29.0, '29:05:00': 29.05, '29:10:00': 29.1, '29:15:00': 29.15, '29:20:00': 29.2, '29:25:00': 29.25, '29:30:00': 29.3, '29:35:00': 29.35, '29:40:00': 29.4, '29:45:00': 29.45, '29:50:00': 29.5, '29:55:00': 29.55}

    data['Mês'] = data['Mês'].map(month)
    #data['Hora Início'] = data['Hora Início'].map(start_hour)
    data['Dia da Semana'] = data['Dia da Semana'].map(day_week)
    # data['Data'] = pd.to_datetime(data['Data']).dt.year
    data['Hora Início'] = data['Hora Início'].map(start_hour)
    return data

In [ ]:
#Executando a função nas planilhas
tv_0_rat = dictionary(tv_0_with_rat)
tv_1_rat = dictionary(tv_1_with_rat)
tv_2_rat = dictionary(tv_2_with_rat)

In [ ]:
tv_0_rat.head(8)

,Unnamed: 0,Unnamed: 0.1,Data,Hora Início,Emissora,Mês,Dia do Mês,Dia da Semana,Total Domicílios | Rat%,AB | Rat%,...,Feminino | Fid%,4-11 anos | Fid%,12-17 anos | Fid%,18-24 anos | Fid%,25-34 anos | Fid%,35-49 anos | Fid%,50-59 anos | Fid%,60+ anos | Fid%,Programa,Categoria
0,0,0,2020-06-01,6.00,tv_0,6,1,1,4.27,2.40,...,89.84,0.0,0.0,0.0,100.0,69.20,100.00,84.31,0.1,JORNALISMO
1,1,1,2020-06-01,6.05,tv_0,6,1,1,4.89,3.02,...,93.16,0.0,0.0,0.0,100.0,100.00,100.00,76.90,0.1,JORNALISMO
2,2,2,2020-06-01,6.10,tv_0,6,1,1,5.74,3.13,...,94.63,0.0,80.0,0.0,100.0,84.24,100.00,84.60,0.1,JORNALISMO
3,3,3,2020-06-01,6.15,tv_0,6,1,1,6.55,3.06,...,96.76,0.0,100.0,0.0,100.0,86.67,89.87,100.00,0.1,JORNALISMO
4,4,4,2020-06-01,6.20,tv_0,6,1,1,7.27,3.49,...,100.00,0.0,100.0,0.0,100.0,95.22,93.24,100.00,0.1,JORNALISMO
5,5,5,2020-06-01,6.25,tv_0,6,1,1,8.34,4.52,...,97.46,0.0,100.0,0.0,100.0,100.00,100.00,90.16,0.1,JORNALISMO
6,6,6,2020-06-01,6.30,tv_0,6,1,1,7.74,3.44,...,88.32,0.0,100.0,0.0,100.0,92.35,66.50,91.17,0.1,JORNALISMO
7,7,7,2020-06-01,6.35,tv_0,6,1,1,6.96,3.92,...,91.18,0.0,100.0,0.0,100.0,100.00,100.00,68.25,0.1,JORNALISMO

In [ ]:
tv_0_with_rat['Hora Início'].unique()

array([ 6.  ,  6.05,  6.1 ,  6.15,  6.2 ,  6.25,  6.3 ,  6.35,  6.4 ,
        6.45,  6.5 ,  6.55,  7.  ,  7.05,  7.1 ,  7.15,  7.2 ,  7.25,
        7.3 ,  7.35,  7.4 ,  7.45,  7.5 ,  7.55,  8.  ,  8.05,  8.1 ,
        8.15,  8.2 ,  8.25,  8.3 ,  8.35,  8.4 ,  8.45,  8.5 ,  8.55,
        9.  ,  9.05,  9.1 ,  9.15,  9.2 ,  9.25,  9.3 ,  9.35,  9.4 ,
        9.45,  9.5 ,  9.55, 10.  , 10.05, 10.1 , 10.15, 10.2 , 10.25,
       10.3 , 10.35, 10.4 , 10.45, 10.5 , 10.55, 11.  , 11.05, 11.1 ,
       11.15, 11.2 , 11.25, 11.3 , 11.35, 11.4 , 11.45, 11.5 , 11.55,
       12.  , 12.05, 12.1 , 12.15, 12.2 , 12.25, 12.3 , 12.35, 12.4 ,
       12.45, 12.5 , 12.55, 13.  , 13.05, 13.1 , 13.15, 13.2 , 13.25,
       13.3 , 13.35, 13.4 , 13.45, 13.5 , 13.55, 14.  , 14.05, 14.1 ,
       14.15, 14.2 , 14.25, 14.3 , 14.35, 14.4 , 14.45, 14.5 , 14.55,
       15.  , 15.05, 15.1 , 15.15, 15.2 , 15.25, 15.3 , 15.35, 15.4 ,
       15.45, 15.5 , 15.55, 16.  , 16.05, 16.1 , 16.15, 16.2 , 16.25,
       16.3 , 16.35, 16.4 , 16.45, 16.5 , 16.55, 17.  , 17.05, 17.1 ,
       17.15, 17.2 , 17.25, 17.3 , 17.35, 17.4 , 17.45, 17.5 , 17.55,
       18.  , 18.05, 18.1 , 18.15, 18.2 , 18.25, 18.3 , 18.35, 18.4 ,
       18.45, 18.5 , 18.55, 19.  , 19.05, 19.1 , 19.15, 19.2 , 19.25,
       19.3 , 19.35, 19.4 , 19.45, 19.5 , 19.55, 20.  , 20.05, 20.1 ,
       20.15, 20.2 , 20.25, 20.3 , 20.35, 20.4 , 20.45, 20.5 , 20.55,
       21.  , 21.05, 21.1 , 21.15, 21.2 , 21.25, 21.3 , 21.35, 21.4 ,
       21.45, 21.5 , 21.55, 22.  , 22.05, 22.1 , 22.15, 22.2 , 22.25,
       22.3 , 22.35, 22.4 , 22.45, 22.5 , 22.55, 23.  , 23.05, 23.1 ,
       23.15, 23.2 , 23.25, 23.3 , 23.35, 23.4 , 23.45, 23.5 , 23.55,
       24.  , 24.05, 24.1 , 24.15, 24.2 , 24.25, 24.3 , 24.35, 24.4 ,
       24.45, 24.5 , 24.55, 25.  , 25.05, 25.1 , 25.15, 25.2 , 25.25,
       25.3 , 25.35, 25.4 , 25.45, 25.5 , 25.55, 26.  , 26.05, 26.1 ,
       26.15, 26.2 , 26.25, 26.3 , 26.35, 26.4 , 26.45, 26.5 , 26.55,
       27.  , 27.05, 27.1 , 27.15, 27.2 , 27.25, 27.3 , 27.35, 27.4 ,
       27.45, 27.5 , 27.55, 28.  , 28.05, 28.1 , 28.15, 28.2 , 28.25,
       28.3 , 28.35, 28.4 , 28.45, 28.5 , 28.55, 29.  , 29.05, 29.1 ,
       29.15, 29.2 , 29.25, 29.3 , 29.35, 29.4 , 29.45, 29.5 , 29.55])

#Criando coluna horarios

In [ ]:
#Definindo os intervalos de hórarios

import numpy as np
conditions = [np.logical_and(tv_0_with_rat['Hora Início'].gt(0), np.less_equal(tv_0_with_rat['Hora Início'], 9.75)),
  np.logical_and(tv_0_with_rat['Hora Início'].gt(9.90), np.less_equal(tv_0_with_rat['Hora Início'],11.75)),
  np.logical_and(tv_0_with_rat['Hora Início'].gt(11.9), np.less_equal(tv_0_with_rat['Hora Início'],14.75)),
  np.logical_and(tv_0_with_rat['Hora Início'].gt(14.9), np.less_equal(tv_0_with_rat['Hora Início'],17.75)),
  np.logical_and(tv_0_with_rat['Hora Início'].gt(17.9), np.less_equal(tv_0_with_rat['Hora Início'],20.75)),
  np.logical_and(tv_0_with_rat['Hora Início'].gt(20.9), np.less_equal(tv_0_with_rat['Hora Início'],24.50)),
  np.logical_and(tv_0_with_rat['Hora Início'].gt(24.6), np.less_equal(tv_0_with_rat['Hora Início'],29.75)),
]

In [ ]:
#Array com os tipos de horários que teremos como base

outputs = ['Manha 1', 'Manha 2' , 'Almoço', 'Tarde', 'Noite 1', 'Noite 2', 'Madrugada']

In [ ]:
#Criando a coluna Horarios nas planilhas

tv_0_rat['Horarios'] = pd.Series(np.select(conditions, outputs))
tv_1_rat['Horarios'] = pd.Series(np.select(conditions, outputs))
tv_2_rat['Horarios'] = pd.Series(np.select(conditions, outputs))

In [ ]:
#Convertendo a coluna Data para apenas o ano 
tv_0_rat['Data'] = pd.to_datetime(tv_0_rat['Data']).dt.year
tv_1_rat['Data'] = pd.to_datetime(tv_0_rat['Data']).dt.year
tv_2_rat['Data'] = pd.to_datetime(tv_0_rat['Data']).dt.year

In [ ]:
tv_0_rat.head(8)

,Unnamed: 0,Unnamed: 0.1,Data,Hora Início,Emissora,Mês,Dia do Mês,Dia da Semana,Total Domicílios | Rat%,AB | Rat%,...,4-11 anos | Fid%,12-17 anos | Fid%,18-24 anos | Fid%,25-34 anos | Fid%,35-49 anos | Fid%,50-59 anos | Fid%,60+ anos | Fid%,Programa,Categoria,Horarios
0,0,0,2020,6.00,tv_0,6,1,1,4.27,2.40,...,0.0,0.0,0.0,100.0,69.20,100.00,84.31,0.1,JORNALISMO,Manha 1
1,1,1,2020,6.05,tv_0,6,1,1,4.89,3.02,...,0.0,0.0,0.0,100.0,100.00,100.00,76.90,0.1,JORNALISMO,Manha 1
2,2,2,2020,6.10,tv_0,6,1,1,5.74,3.13,...,0.0,80.0,0.0,100.0,84.24,100.00,84.60,0.1,JORNALISMO,Manha 1
3,3,3,2020,6.15,tv_0,6,1,1,6.55,3.06,...,0.0,100.0,0.0,100.0,86.67,89.87,100.00,0.1,JORNALISMO,Manha 1
4,4,4,2020,6.20,tv_0,6,1,1,7.27,3.49,...,0.0,100.0,0.0,100.0,95.22,93.24,100.00,0.1,JORNALISMO,Manha 1
5,5,5,2020,6.25,tv_0,6,1,1,8.34,4.52,...,0.0,100.0,0.0,100.0,100.00,100.00,90.16,0.1,JORNALISMO,Manha 1
6,6,6,2020,6.30,tv_0,6,1,1,7.74,3.44,...,0.0,100.0,0.0,100.0,92.35,66.50,91.17,0.1,JORNALISMO,Manha 1
7,7,7,2020,6.35,tv_0,6,1,1,6.96,3.92,...,0.0,100.0,0.0,100.0,100.00,100.00,68.25,0.1,JORNALISMO,Manha 1

#One-Hot Encoding

Convertendo categorias em colunas

In [ ]:
tv_0_rat_cat = pd.get_dummies(tv_0_rat, columns=['Categoria'])

tv_1_rat_cat = pd.get_dummies(tv_1_rat, columns=['Categoria'])

tv_2_rat_cat = pd.get_dummies(tv_2_rat, columns=['Categoria'])

Convertendo dia da semana em uma coluna

In [ ]:
tv_0_rat_final = pd.get_dummies(tv_0_rat_cat, columns=['Dia da Semana'])
tv_1_rat_final = pd.get_dummies(tv_1_rat_cat, columns=['Dia da Semana'])
tv_2_rat_final = pd.get_dummies(tv_2_rat_cat, columns=['Dia da Semana'])

In [ ]:
from google.colab.data_table import DataTable
DataTable.max_columns = 120

tv_0_rat_final.head(8)

,Unnamed: 0,Unnamed: 0.1,Data,Hora Início,Emissora,Mês,Dia do Mês,Total Domicílios | Rat%,AB | Rat%,C1 | Rat%,...,Categoria_SHOW,Categoria_SORTEIO,Categoria_TELE VENDAS,Dia da Semana_1,Dia da Semana_2,Dia da Semana_3,Dia da Semana_4,Dia da Semana_5,Dia da Semana_6,Dia da Semana_7
0,0,0,2020,6.00,tv_0,6,1,4.27,2.40,0.31,...,0,0,0,1,0,0,0,0,0,0
1,1,1,2020,6.05,tv_0,6,1,4.89,3.02,0.51,...,0,0,0,1,0,0,0,0,0,0
2,2,2,2020,6.10,tv_0,6,1,5.74,3.13,1.53,...,0,0,0,1,0,0,0,0,0,0
3,3,3,2020,6.15,tv_0,6,1,6.55,3.06,1.86,...,0,0,0,1,0,0,0,0,0,0
4,4,4,2020,6.20,tv_0,6,1,7.27,3.49,2.18,...,0,0,0,1,0,0,0,0,0,0
5,5,5,2020,6.25,tv_0,6,1,8.34,4.52,2.18,...,0,0,0,1,0,0,0,0,0,0
6,6,6,2020,6.30,tv_0,6,1,7.74,3.44,2.50,...,0,0,0,1,0,0,0,0,0,0
7,7,7,2020,6.35,tv_0,6,1,6.96,3.92,1.87,...,0,0,0,1,0,0,0,0,0,0

#Gerando os csv com todas as features adicionadas

In [ ]:
# Convertendo para .csv

tv_0_rat_final.to_csv('tv_0_ukn_5_min.csv')
files.download('tv_0_ukn_5_min.csv')

tv_1_rat_final.to_csv('tv_1_ukn.csv')
files.download('tv_1_ukn.csv')

tv_2_rat_final.to_csv('tv_2_ukn.csv')
files.download('tv_2_ukn.csv')